
![picture](https://cdn.analyticsvidhya.com/wp-content/uploads/2019/09/pytorch.png)



------------------------------------------------------------------------
Please if you are working on Colab save a copy and rename using your name.

Don't edit directly the original file.

Thank you.


-----------------------------------------------------------------------


# Why PyTorch
Pytorch is important for deep learning because it makes building, training, and experimenting with neural networks easy and fast.

# Definition


PyTorch is a Python-based library used to build neural networks.

It provides two main features:

* An n-dimensional Tensor object

* Automatic differentiation for building and training neural networks


## Tensors

At its core, PyTorch is a library for processing tensors. Tensors are a specialized data structure similar to NumPy's ndarrays, except that tensors can run on GPUs (to accelerate their numeric computations). This is a major advantage of using tensors. A tensor can be a number, vector, matrix, or any n-dimensional array.


![picture](https://tse3.mm.bing.net/th/id/OIP.gq-qHnpwhiReloHgqP6sdQHaCl?rs=1&pid=ImgDetMain&o=7&rm=3)

PyTorch supports multiple types of tensors, including:

1. FloatTensor: stores numbers as 32-bit floating-point values.

2. DoubleTensor: stores numbers as 64-bit floating-point values (higher precision).

3. HalfTensor: stores numbers as 16-bit floating-point values (lower precision).

4. IntTensor: stores numbers as 32-bit signed integers.

5. LongTensor: stores numbers as 64-bit signed integers.


# Setup

In [ ]:
# !conda install pytorch torchvision -c pytorch
# # or with GPU
# ! conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

#https://pytorch.org/

In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


# Tensor creation

### Scalar

In [3]:
t1 = torch.tensor(4)
print(t1)

tensor(4)


### 1D tensor (vector)

In [4]:
t2 = torch.tensor([1., 2, 3, 4], dtype=torch.float32)
print(t2)

tensor([1., 2., 3., 4.])


In [4]:
t3 = torch.tensor([1., 2, 3, 4], dtype=torch.float64)
print(t3 + t2)

tensor([2., 4., 6., 8.], dtype=torch.float64)


### 2D tensor (matrix)

In [5]:
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])

print(t3)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


### 3D tensor

In [6]:
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
print(t4)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


### Tensor filled with zeros

In [7]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor filled with ones

In [8]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Tensor filled with random values

In [9]:
# setting the random seed for pytorch
torch.manual_seed(42)

## torch.randn returns a tensor filled with random numbers from a normal distribution with mean `0` and variance `1`
torch.randn(3,3)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [10]:
# torch.randint returns a tensor filled with random integers generated uniformly
torch.randint(0, 10, (3,3))

tensor([[9, 6, 3],
        [1, 9, 3],
        [1, 9, 7]])

In [11]:
## torch.rand returns a tensor filled with random numbers from a uniform distribution on the interval `[0, 1)`
torch.rand(3,3)

tensor([[0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040]])

# Attributes of a tensor

In [12]:
a = torch.rand(3,4)
print(a, '\n')

print(f"Shape of tensor: {a.shape}")
# print(f"Shape of tensor: {a.size()}")
print(f"Data type of tensor: {a.dtype}")
print(f"Number of dimenssion: {a.ndim}")
print(f"Device tensor is stored on: {a.device}")

tensor([[0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539, 0.1952]]) 

Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Number of dimenssion: 2
Device tensor is stored on: cpu


# Torch tensors and numpy conversion

### From tensor to numpy

In [13]:
## Tensor to numpy array
a = torch.rand(3,3)
print(a, '\n')

## convert a into numpy array b
b = a.numpy()
print(b, '\n')

## update the tensor a by adding a value to it
b +=2
print(a, '\n')

tensor([[0.0050, 0.3068, 0.1165],
        [0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913]]) 

[[0.00504577 0.30681974 0.11648858]
 [0.91026944 0.64401567 0.70710677]
 [0.6581306  0.491302   0.89130414]] 

tensor([[2.0050, 2.3068, 2.1165],
        [2.9103, 2.6440, 2.7071],
        [2.6581, 2.4913, 2.8913]]) 



Note: if the tensor a is on the cpu and not the gpu, then both a and b will share/point to the same memory

### From numpy to tensor

In [14]:
# torch.set_printoptions(precision=8)
import numpy as np

a = np.random.rand(3,3)
print(a, '\n')

## convert array a into tensor b
b = torch.from_numpy(a)#.clone()
print(b, '\n')
a += 2
print(b)

[[0.30792415 0.02327221 0.16367908]
 [0.90020479 0.34264891 0.10010548]
 [0.83838991 0.70375053 0.37502667]] 

tensor([[0.3079, 0.0233, 0.1637],
        [0.9002, 0.3426, 0.1001],
        [0.8384, 0.7038, 0.3750]], dtype=torch.float64) 

tensor([[2.3079, 2.0233, 2.1637],
        [2.9002, 2.3426, 2.1001],
        [2.8384, 2.7038, 2.3750]], dtype=torch.float64)


### Move tensor to a specific  GPU/CPU device

In [15]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
a = torch.ones(2, device=device)
print(a)

tensor([1., 1.], device='cuda:0')


In [16]:
#Move to GPU if available
if torch.cuda.is_available():
  device = torch.device('cuda')
  print(device)

  x = torch.ones(5, device=device)
  y = torch.ones(5).to(device)
  z = x+y

  z.numpy()

cuda


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Note: if we want to convert the z below directly to numpy (z.numpy()), this will return an error, because numpy can only handle cpu tensors; So we wil have to bring first z to cpu first and later on do the convertion

In [ ]:
# z.to("cpu").numpy()
z.cpu().numpy()

array([2., 2., 2., 2., 2.], dtype=float32)

# Operations on tensors

## Standard numpy-like indexing and slicing

In [17]:
a =  torch.randint(0, 10, (4,3))
print(a, '\n')

print(a[0,0])
print(f"First row: {a[0]}")
print(f"First column: {a[:, 0]}")
print(f"Last column: {a[:, -1]}")
a[:,1] = 0
print(a)

tensor([[8, 6, 0],
        [0, 0, 0],
        [1, 3, 0],
        [1, 1, 7]]) 

tensor(8)
First row: tensor([8, 6, 0])
First column: tensor([8, 0, 1, 1])
Last column: tensor([0, 0, 0, 7])
tensor([[8, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [1, 0, 7]])


### Exercise 1

Consider the array x below and reply to the following questions:
1. Convert x to a tensor
2. Get the attributes of the obtained tensor(shape, dimension, type, device)
3. Get the first element in the second dim of the second block (9)
4. select the third row in each block

## Arithmetic operations

### Addition, substraction,  division

For addition, substraction and division we can either use torch.add, torch.sub, torch.div or +,  - and /

In [18]:
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)
print(a, '\n')
print(b)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 

tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])


In [19]:
## compute sum of a and b
print(a + b) #torch.add(a,b)

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])


In [20]:
## compute a -b
a - b #torch.sub(a,b)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])

In [21]:
##compute a / b
a / b #torch.div(a, b)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])

In [22]:
torch.sum(b, dim=0)

tensor([2.3356, 0.1672, 0.6376])

### Multiplication



#### Elementwise multiplication

In [23]:
##
a * b

tensor([[ 0.0900,  0.0689,  0.1898],
        [ 0.2557,  1.8974,  0.1843],
        [ 2.1154, -0.8435,  0.3773]])

#### matrix multiplication

In [24]:
##using torch.mm
torch.mm(a, b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [ ]:
##using torch.matmul
torch.matmul(a,b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [ ]:
##using @
a @ b

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

## Reshape, Transpose, concatenate, flatten  and squeeze tensors

### Reshaping

In [27]:
torch.manual_seed(42)

a = torch.randn(3,4)
print(a.shape)

b = a.reshape(-1, 1) #a.view(-1,1)
print(b.shape)

c = a.reshape(6,2)
print(c.shape)

torch.Size([3, 4])
torch.Size([12, 1])
torch.Size([6, 2])


### Transpose

In [28]:
a_t = a.T #torch.t(a)
print(a_t.shape)

torch.Size([4, 3])


### Concatenating

In [29]:
b = torch.randn(1, 4)
print(b.shape)
concat = torch.cat((a, b), dim=0)
print(concat.shape)

torch.Size([1, 4])
torch.Size([4, 4])


### Flattening

In [30]:
flat_vect = a.flatten()
print(flat_vect)
flat_vect.shape

tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
         0.4617,  0.2674,  0.5349,  0.8094])


torch.Size([12])

### Squeeze a tensor


To compress tensors along their singleton dimensions we can use the .squeeze() method and use the .unsqueeze() method to do the opposite.

In [31]:
x = torch.randn(1, 10)
y = x.squeeze()
y.shape

torch.Size([10])

## In-place operations

In [32]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(y, '\n')
y.add_(x)
x.sub_(y)

print(y, '\n')
print(x)

tensor([[0.6581, 0.4913],
        [0.8913, 0.1447]]) 

tensor([[0.7746, 1.4016],
        [1.5353, 0.8518]]) 

tensor([[-0.6581, -0.4913],
        [-0.8913, -0.1447]])


## Get the value of a tensor

In [33]:
x = torch.rand(5,3)
print(x[1,1])
print(x[1,1].item())

tensor(0.6532)
0.6532081365585327


# Exercise 2:

* Create two random tensors of shape (4, 3) and send them both to the GPU. Set torch.manual_seed(1234) when creating the tensors.
* Perform a matrix multiplication on these two tensors;
* Convert the result to a Numpy array.

# Exercise 3:

Create a function that takes in a square matrix A and returns a 2D tensor consisting of a flattened A with the index of each element appended to this tensor in the row dimension, e.g.,



 \begin{equation*}
 A=
 \begin{bmatrix}
  2 & 3 \\
  4 & -2
\end{bmatrix}, \ \
output = \begin{bmatrix}
  0 & 2 \\
  1 & 3 \\
  2 & 4 \\
  3 & -2
\end{bmatrix}
\end{equation*}


In [35]:
def function_concat(A):
    # Flatten the input tensor A
    flattened_A = A.flatten()

    # Create a tensor of indices from 0 to num_elements-1
    # Ensure the dtype matches that of A for consistent stacking
    indices = torch.arange(flattened_A.numel(), dtype=A.dtype)

    # Stack the indices and the flattened tensor column-wise
    # The result will be a 2D tensor where the first column is indices and the second is values
    output = torch.stack((indices, flattened_A), dim=1)
    return output

## TEST YOUR CODE HERE ##
A = torch.tensor([[2,3],[4,-2]])
print(function_concat(A))

tensor([[ 0,  2],
        [ 1,  3],
        [ 2,  4],
        [ 3, -2]])


# Exercise 4:

Write a function to check device-compatiblity with computations. Fill the missing part in the code below.

Note: You have to set the device when creating each tensor.

In [ ]:
##  TEST YOUR CODE HERE ##

dim=10000
print(f"Execution time when using the cpu: {cpu_gpu(dim, device='cpu')}")

Execution time when using the cpu: 15.124581575393677


In [ ]:
print(f"Execution time when using the gpu: {cpu_gpu(dim, device='cuda')}")

Execution time when using the gpu: 0.021338462829589844


In [ ]:
print(f"Time ratio {(0.034049034118652344/18.075910568237305)*100}")

Time ratio 0.188366909595596


#### Comment the results

# Extra reading

1. https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

2. https://pytorch.org/tutorials/
